services:
  check_ssl:
    image: ghcr.io/devtoto/check_ssl:latest
    container_name: check_ssl
    restart: unless-stopped
    environment:
      TZ: Europe/Zurich
    volumes:
      - ./hosts.txt:/app/hosts.txt
      - ./certs:/var/www/html/certs
    ports:
      - "8080:80"
    networks:
      - ssl_network

networks:
  ssl_network:
    driver: bridge
