services:
  ssl-checker:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./hosts.txt:/app/hosts.txt
    environment:
      - TZ=UTC
